[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."upload"]
  external_node_modules = ["multiparty"]
  node_bundler = "esbuild"

[functions."rag"]
  external_node_modules = ["llamaindex", "pdf-parse"]
  node_bundler = "esbuild"

[functions."chat"]
  external_node_modules = ["@google/genai"]
  node_bundler = "esbuild"

[functions."pages"]
  external_node_modules = []
  node_bundler = "esbuild"
